export const routes = {
  Home: '/',
  BackEndLogin: '/login',
  BackEndSignUp: '/signup',
  ClientLogin: '/login',
  ClientSignup: '/register',
  ClientFeedBackForm: '/feedback',
  Dashboard: '/dashboard',
  BatchesPage: '/batches',
  BatchesDetailsPage: '/batchdetails',
  SubmitFeedback: '/submitFeedback',
  StudentSignup: '/registerStudent',
  StudentHome: '/studentHome',
  AddBatch: '/addBatch',
  AddStudent: '/addStudent',
  BackEndEditBatches: '/batches',
  Authentication: '/users',
  FormById: '/getFormById',
};
